// Color scheme variants for popular themes
// Each theme has 4 variants: A (original), B (alternative), C (high contrast), D (inverted/complementary)

export const COLOR_VARIANTS = {
  // 1. Default Theme
  default: {
    variantA: {
      name: '经典蓝',
      bgApp: 'bg-slate-50',
      bgPanel: 'bg-white',
      textMain: 'text-slate-900',
      textMuted: 'text-slate-500',
      primary: 'bg-blue-600 hover:bg-blue-700 text-white shadow-sm',
      border: 'border border-slate-200',
      shadow: 'shadow-sm',
      inputStyle: 'bg-white border-slate-300 focus:ring-2 focus:ring-blue-500',
    },
    variantB: {
      name: '翡翠绿',
      bgApp: 'bg-emerald-50',
      bgPanel: 'bg-white',
      textMain: 'text-emerald-900',
      textMuted: 'text-emerald-600',
      primary: 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm',
      border: 'border border-emerald-200',
      shadow: 'shadow-emerald-100',
      inputStyle: 'bg-white border-emerald-300 focus:ring-2 focus:ring-emerald-500',
    },
    variantC: {
      name: '高对比',
      bgApp: 'bg-white',
      bgPanel: 'bg-gray-50',
      textMain: 'text-black',
      textMuted: 'text-gray-700',
      primary: 'bg-black hover:bg-gray-900 text-white shadow-md',
      border: 'border-2 border-gray-900',
      shadow: 'shadow-lg',
      inputStyle: 'bg-white border-2 border-black focus:ring-4 focus:ring-gray-400',
    },
    variantD: {
      name: '暗夜橙',
      bgApp: 'bg-gray-900',
      bgPanel: 'bg-gray-800',
      textMain: 'text-gray-100',
      textMuted: 'text-gray-400',
      primary: 'bg-orange-600 hover:bg-orange-700 text-white shadow-sm',
      border: 'border border-gray-700',
      shadow: 'shadow-orange-900/20',
      inputStyle: 'bg-gray-700 border-gray-600 text-white focus:ring-2 focus:ring-orange-500',
    },
  },

  // 2. Glassmorphism
  glassmorphism: {
    variantA: {
      name: '紫粉渐变',
      bgApp: 'bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500',
      bgPanel: 'bg-white/20 backdrop-blur-xl border border-white/30',
      textMain: 'text-white drop-shadow-md',
      textMuted: 'text-white/80',
      primary: 'bg-white/30 hover:bg-white/40 border border-white/50 text-white shadow-lg backdrop-blur-md',
      border: 'border border-white/20',
      shadow: 'shadow-2xl',
      inputStyle: 'bg-black/20 border border-white/10 text-white placeholder-white/50',
    },
    variantB: {
      name: '青蓝海洋',
      bgApp: 'bg-gradient-to-br from-cyan-400 via-blue-500 to-indigo-600',
      bgPanel: 'bg-white/20 backdrop-blur-xl border border-white/30',
      textMain: 'text-white drop-shadow-md',
      textMuted: 'text-white/80',
      primary: 'bg-cyan-400/30 hover:bg-cyan-400/40 border border-white/50 text-white shadow-lg backdrop-blur-md',
      border: 'border border-cyan-200/20',
      shadow: 'shadow-2xl shadow-blue-500/20',
      inputStyle: 'bg-blue-900/20 border border-cyan-300/10 text-white placeholder-white/50',
    },
    variantC: {
      name: '日落金橙',
      bgApp: 'bg-gradient-to-br from-amber-400 via-orange-500 to-red-500',
      bgPanel: 'bg-white/25 backdrop-blur-xl border border-white/40',
      textMain: 'text-white drop-shadow-lg',
      textMuted: 'text-white/90',
      primary: 'bg-white/35 hover:bg-white/45 border border-white/60 text-white shadow-xl backdrop-blur-md',
      border: 'border border-white/25',
      shadow: 'shadow-2xl shadow-orange-500/30',
      inputStyle: 'bg-black/25 border border-white/15 text-white placeholder-white/60',
    },
    variantD: {
      name: '森林翠绿',
      bgApp: 'bg-gradient-to-br from-emerald-500 via-teal-500 to-cyan-600',
      bgPanel: 'bg-black/20 backdrop-blur-xl border border-emerald-300/30',
      textMain: 'text-white drop-shadow-md',
      textMuted: 'text-emerald-100/80',
      primary: 'bg-emerald-400/30 hover:bg-emerald-400/40 border border-emerald-200/50 text-white shadow-lg backdrop-blur-md',
      border: 'border border-emerald-300/20',
      shadow: 'shadow-2xl shadow-emerald-500/20',
      inputStyle: 'bg-emerald-900/20 border border-emerald-300/10 text-white placeholder-emerald-100/50',
    },
  },

  // 3. Brutalism
  brutalism: {
    variantA: {
      name: '经典橙黑',
      bgApp: 'bg-[#ff9900]',
      bgPanel: 'bg-white border-4 border-black',
      textMain: 'text-black font-black uppercase tracking-tighter',
      textMuted: 'text-gray-800',
      primary: 'bg-black text-white hover:bg-white hover:text-black border-4 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-x-[4px] hover:translate-y-[4px]',
      border: 'border-4 border-black',
      shadow: 'shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]',
      inputStyle: 'bg-white border-4 border-black text-black font-bold focus:bg-[#ffff00]',
    },
    variantB: {
      name: '电光粉',
      bgApp: 'bg-[#ff00ff]',
      bgPanel: 'bg-[#ffff00] border-4 border-black',
      textMain: 'text-black font-black uppercase tracking-tighter',
      textMuted: 'text-gray-900',
      primary: 'bg-[#00ffff] text-black hover:bg-black hover:text-[#00ffff] border-4 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-x-[4px] hover:translate-y-[4px]',
      border: 'border-4 border-black',
      shadow: 'shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]',
      inputStyle: 'bg-[#ffff00] border-4 border-black text-black font-bold focus:bg-[#00ffff]',
    },
    variantC: {
      name: '红白冲击',
      bgApp: 'bg-[#ff0000]',
      bgPanel: 'bg-white border-8 border-black',
      textMain: 'text-black font-black uppercase tracking-tighter',
      textMuted: 'text-gray-900',
      primary: 'bg-black text-white hover:bg-white hover:text-black border-8 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-x-[8px] hover:translate-y-[8px]',
      border: 'border-8 border-black',
      shadow: 'shadow-[12px_12px_0px_0px_rgba(0,0,0,1)]',
      inputStyle: 'bg-white border-8 border-black text-black font-bold focus:bg-[#ff0000] focus:text-white',
    },
    variantD: {
      name: '霓虹绿',
      bgApp: 'bg-[#00ff00]',
      bgPanel: 'bg-black border-4 border-[#00ff00]',
      textMain: 'text-[#00ff00] font-black uppercase tracking-tighter',
      textMuted: 'text-[#00ff00]/80',
      primary: 'bg-[#00ff00] text-black hover:bg-black hover:text-[#00ff00] border-4 border-[#00ff00] shadow-[4px_4px_0px_0px_rgba(0,255,0,1)] hover:shadow-none hover:translate-x-[4px] hover:translate-y-[4px]',
      border: 'border-4 border-[#00ff00]',
      shadow: 'shadow-[8px_8px_0px_0px_rgba(0,255,0,1)]',
      inputStyle: 'bg-black border-4 border-[#00ff00] text-[#00ff00] font-bold focus:bg-[#00ff00] focus:text-black',
    },
  },

  // 4. Minimalism
  minimalism: {
    variantA: {
      name: '纯白简约',
      bgApp: 'bg-white',
      bgPanel: 'bg-white',
      textMain: 'text-gray-900',
      textMuted: 'text-gray-600',
      primary: 'bg-black text-white rounded-full px-8 border border-transparent hover:bg-gray-800',
      border: 'border border-gray-200',
      shadow: 'shadow-none',
      inputStyle: 'bg-transparent border-b border-gray-300 px-0 text-gray-900',
    },
    variantB: {
      name: '米色温暖',
      bgApp: 'bg-[#faf8f5]',
      bgPanel: 'bg-[#faf8f5]',
      textMain: 'text-[#2a2a2a]',
      textMuted: 'text-[#6a6a6a]',
      primary: 'bg-[#3a3a3a] text-[#faf8f5] rounded-full px-8 border border-transparent hover:bg-[#1a1a1a]',
      border: 'border border-[#e5e0d8]',
      shadow: 'shadow-none',
      inputStyle: 'bg-transparent border-b border-[#d5d0c8] px-0 text-[#2a2a2a]',
    },
    variantC: {
      name: '极简黑白',
      bgApp: 'bg-white',
      bgPanel: 'bg-white',
      textMain: 'text-black',
      textMuted: 'text-gray-800',
      primary: 'bg-black text-white rounded-none px-8 border-2 border-black hover:bg-white hover:text-black',
      border: 'border-2 border-black',
      shadow: 'shadow-none',
      inputStyle: 'bg-transparent border-b-2 border-black px-0 text-black',
    },
    variantD: {
      name: '暗黑极简',
      bgApp: 'bg-[#0a0a0a]',
      bgPanel: 'bg-[#0a0a0a]',
      textMain: 'text-white',
      textMuted: 'text-gray-400',
      primary: 'bg-white text-black rounded-full px-8 border border-transparent hover:bg-gray-200',
      border: 'border border-gray-800',
      shadow: 'shadow-none',
      inputStyle: 'bg-transparent border-b border-gray-700 px-0 text-white',
    },
  },

  // 5. Material Design
  'material-design': {
    variantA: {
      name: '经典紫',
      bgApp: 'bg-gray-100',
      bgPanel: 'bg-white',
      textMain: 'text-gray-900',
      textMuted: 'text-gray-600',
      primary: 'bg-[#6200ee] text-white shadow-md hover:shadow-lg transition-all uppercase tracking-wider font-medium',
      border: 'border-0',
      shadow: 'shadow-md',
      inputStyle: 'bg-gray-50 border-b-2 border-gray-300 focus:border-[#6200ee] rounded-t',
    },
    variantB: {
      name: '活力橙',
      bgApp: 'bg-orange-50',
      bgPanel: 'bg-white',
      textMain: 'text-gray-900',
      textMuted: 'text-gray-600',
      primary: 'bg-[#ff6d00] text-white shadow-md hover:shadow-lg transition-all uppercase tracking-wider font-medium',
      border: 'border-0',
      shadow: 'shadow-md shadow-orange-100',
      inputStyle: 'bg-orange-50 border-b-2 border-orange-300 focus:border-[#ff6d00] rounded-t',
    },
    variantC: {
      name: '深海蓝',
      bgApp: 'bg-blue-50',
      bgPanel: 'bg-white',
      textMain: 'text-gray-900',
      textMuted: 'text-gray-600',
      primary: 'bg-[#0d47a1] text-white shadow-lg hover:shadow-xl transition-all uppercase tracking-wider font-medium',
      border: 'border-0',
      shadow: 'shadow-lg shadow-blue-100',
      inputStyle: 'bg-blue-50 border-b-2 border-blue-300 focus:border-[#0d47a1] rounded-t',
    },
    variantD: {
      name: '暗色主题',
      bgApp: 'bg-[#121212]',
      bgPanel: 'bg-[#1e1e1e]',
      textMain: 'text-white',
      textMuted: 'text-gray-400',
      primary: 'bg-[#bb86fc] text-black shadow-md hover:shadow-lg transition-all uppercase tracking-wider font-medium',
      border: 'border-0',
      shadow: 'shadow-md shadow-purple-900/50',
      inputStyle: 'bg-[#2c2c2c] border-b-2 border-gray-700 focus:border-[#bb86fc] rounded-t text-white',
    },
  },

  // 6. Neumorphism
  neumorphism: {
    variantA: {
      name: '经典灰',
      bgApp: 'bg-[#e0e5ec]',
      bgPanel: 'bg-[#e0e5ec]',
      textMain: 'text-[#4a5568]',
      textMuted: 'text-[#718096]',
      primary: 'bg-[#e0e5ec] text-[#4a5568] shadow-[6px_6px_12px_#b8b9be,-6px_-6px_12px_#ffffff] active:shadow-[inset_6px_6px_12px_#b8b9be,inset_-6px_-6px_12px_#ffffff]',
      border: 'border-0',
      shadow: 'shadow-[9px_9px_16px_rgb(163,177,198,0.6),-9px_-9px_16px_rgba(255,255,255,0.5)]',
      inputStyle: 'bg-[#e0e5ec] shadow-[inset_5px_5px_10px_#b8b9be,inset_-5px_-5px_10px_#ffffff] border-none text-[#4a5568]',
    },
    variantB: {
      name: '粉色柔和',
      bgApp: 'bg-[#f5e6f0]',
      bgPanel: 'bg-[#f5e6f0]',
      textMain: 'text-[#5a4568]',
      textMuted: 'text-[#8a7096]',
      primary: 'bg-[#f5e6f0] text-[#5a4568] shadow-[6px_6px_12px_#d8c9ce,-6px_-6px_12px_#ffffff] active:shadow-[inset_6px_6px_12px_#d8c9ce,inset_-6px_-6px_12px_#ffffff]',
      border: 'border-0',
      shadow: 'shadow-[9px_9px_16px_rgb(213,177,198,0.6),-9px_-9px_16px_rgba(255,255,255,0.5)]',
      inputStyle: 'bg-[#f5e6f0] shadow-[inset_5px_5px_10px_#d8c9ce,inset_-5px_-5px_10px_#ffffff] border-none text-[#5a4568]',
    },
    variantC: {
      name: '蓝色清新',
      bgApp: 'bg-[#e0f0f5]',
      bgPanel: 'bg-[#e0f0f5]',
      textMain: 'text-[#2a4a5a]',
      textMuted: 'text-[#5a7a8a]',
      primary: 'bg-[#e0f0f5] text-[#2a4a5a] shadow-[6px_6px_12px_#b8d8e8,-6px_-6px_12px_#ffffff] active:shadow-[inset_6px_6px_12px_#b8d8e8,inset_-6px_-6px_12px_#ffffff]',
      border: 'border-0',
      shadow: 'shadow-[9px_9px_16px_rgb(163,207,228,0.6),-9px_-9px_16px_rgba(255,255,255,0.5)]',
      inputStyle: 'bg-[#e0f0f5] shadow-[inset_5px_5px_10px_#b8d8e8,inset_-5px_-5px_10px_#ffffff] border-none text-[#2a4a5a]',
    },
    variantD: {
      name: '暗色新拟态',
      bgApp: 'bg-[#2a2a3a]',
      bgPanel: 'bg-[#2a2a3a]',
      textMain: 'text-[#e0e0f0]',
      textMuted: 'text-[#a0a0b0]',
      primary: 'bg-[#2a2a3a] text-[#e0e0f0] shadow-[6px_6px_12px_#1a1a2a,-6px_-6px_12px_#3a3a4a] active:shadow-[inset_6px_6px_12px_#1a1a2a,inset_-6px_-6px_12px_#3a3a4a]',
      border: 'border-0',
      shadow: 'shadow-[9px_9px_16px_rgb(20,20,30,0.6),-9px_-9px_16px_rgba(60,60,80,0.5)]',
      inputStyle: 'bg-[#2a2a3a] shadow-[inset_5px_5px_10px_#1a1a2a,inset_-5px_-5px_10px_#3a3a4a] border-none text-[#e0e0f0]',
    },
  },

  // 7. Y2K
  y2k: {
    variantA: {
      name: '经典Y2K',
      bgApp: 'bg-gradient-to-r from-[#ff00cc] to-[#333399]',
      bgPanel: 'bg-white/90 border-2 border-pink-500',
      textMain: 'text-blue-900',
      textMuted: 'text-blue-700',
      primary: 'bg-gradient-to-r from-cyan-400 to-blue-500 text-white border-2 border-white ring-2 ring-pink-500 rounded-full italic font-bold shadow-[0_0_10px_#ff00ff]',
      border: 'border-2 border-pink-400',
      shadow: 'shadow-[5px_5px_0px_rgba(0,255,255,0.5)]',
      inputStyle: 'bg-white border-2 border-blue-400 text-blue-800 placeholder-pink-300',
    },
    variantB: {
      name: '绿色矩阵',
      bgApp: 'bg-gradient-to-r from-[#00ff00] to-[#003300]',
      bgPanel: 'bg-black/90 border-2 border-green-500',
      textMain: 'text-green-400',
      textMuted: 'text-green-300',
      primary: 'bg-gradient-to-r from-green-400 to-green-600 text-black border-2 border-green-300 ring-2 ring-green-500 rounded-full italic font-bold shadow-[0_0_10px_#00ff00]',
      border: 'border-2 border-green-400',
      shadow: 'shadow-[5px_5px_0px_rgba(0,255,0,0.5)]',
      inputStyle: 'bg-black border-2 border-green-400 text-green-400 placeholder-green-600',
    },
    variantC: {
      name: '橙色爆炸',
      bgApp: 'bg-gradient-to-r from-[#ff6600] to-[#ff0066]',
      bgPanel: 'bg-yellow-100/90 border-2 border-orange-500',
      textMain: 'text-red-900',
      textMuted: 'text-orange-700',
      primary: 'bg-gradient-to-r from-orange-400 to-red-500 text-white border-2 border-yellow-300 ring-2 ring-orange-500 rounded-full italic font-bold shadow-[0_0_10px_#ff6600]',
      border: 'border-2 border-orange-400',
      shadow: 'shadow-[5px_5px_0px_rgba(255,102,0,0.5)]',
      inputStyle: 'bg-yellow-100 border-2 border-orange-400 text-red-800 placeholder-orange-300',
    },
    variantD: {
      name: '紫色梦幻',
      bgApp: 'bg-gradient-to-r from-[#9900ff] to-[#0099ff]',
      bgPanel: 'bg-purple-100/90 border-2 border-purple-500',
      textMain: 'text-purple-900',
      textMuted: 'text-purple-700',
      primary: 'bg-gradient-to-r from-purple-400 to-blue-400 text-white border-2 border-purple-300 ring-2 ring-blue-500 rounded-full italic font-bold shadow-[0_0_10px_#9900ff]',
      border: 'border-2 border-purple-400',
      shadow: 'shadow-[5px_5px_0px_rgba(153,0,255,0.5)]',
      inputStyle: 'bg-purple-100 border-2 border-purple-400 text-purple-800 placeholder-purple-300',
    },
  },

  // 8. Synthwave
  synthwave: {
    variantA: {
      name: '经典合成波',
      bgApp: 'bg-[#120428]',
      bgPanel: 'bg-[#240b4c] border border-pink-500',
      textMain: 'text-cyan-300',
      textMuted: 'text-pink-400',
      primary: 'bg-gradient-to-r from-pink-500 to-yellow-500 text-white border border-white/20',
      border: 'border border-pink-500/50',
      shadow: 'shadow-[0_0_15px_rgba(255,0,255,0.4)]',
      inputStyle: 'bg-[#1a0736] border border-cyan-500 text-cyan-300',
    },
    variantB: {
      name: '蓝紫电光',
      bgApp: 'bg-[#0a0420]',
      bgPanel: 'bg-[#1a0b3c] border border-blue-500',
      textMain: 'text-blue-300',
      textMuted: 'text-purple-400',
      primary: 'bg-gradient-to-r from-blue-500 to-purple-500 text-white border border-white/20',
      border: 'border border-blue-500/50',
      shadow: 'shadow-[0_0_15px_rgba(0,100,255,0.4)]',
      inputStyle: 'bg-[#0a0630] border border-blue-500 text-blue-300',
    },
    variantC: {
      name: '绿色矩阵',
      bgApp: 'bg-[#001a00]',
      bgPanel: 'bg-[#003300] border border-green-500',
      textMain: 'text-green-300',
      textMuted: 'text-green-400',
      primary: 'bg-gradient-to-r from-green-500 to-cyan-500 text-black border border-green-300/20',
      border: 'border border-green-500/50',
      shadow: 'shadow-[0_0_15px_rgba(0,255,100,0.4)]',
      inputStyle: 'bg-[#001a00] border border-green-500 text-green-300',
    },
    variantD: {
      name: '橙红日落',
      bgApp: 'bg-[#1a0404]',
      bgPanel: 'bg-[#2a0808] border border-orange-500',
      textMain: 'text-orange-300',
      textMuted: 'text-red-400',
      primary: 'bg-gradient-to-r from-orange-500 to-red-500 text-white border border-white/20',
      border: 'border border-orange-500/50',
      shadow: 'shadow-[0_0_15px_rgba(255,100,0,0.4)]',
      inputStyle: 'bg-[#1a0404] border border-orange-500 text-orange-300',
    },
  },

  // 9. Vaporwave
  vaporwave: {
    variantA: {
      name: '经典蒸汽波',
      bgApp: 'bg-gradient-to-b from-[#ff71ce] via-[#01cdfe] to-[#05ffa1]',
      bgPanel: 'bg-white/80',
      textMain: 'text-[#2b1d52] italic',
      textMuted: 'text-[#4b3d72]',
      primary: 'bg-gradient-to-r from-[#ff71ce] to-[#01cdfe] text-white italic shadow-[4px_4px_0_#2b1d52]',
      border: 'border border-pink-300',
      shadow: 'shadow-lg',
      inputStyle: 'bg-white/90 border-2 border-pink-300 text-purple-900',
    },
    variantB: {
      name: '日落橙紫',
      bgApp: 'bg-gradient-to-b from-[#ff9a56] via-[#ff6b9d] to-[#c06c84]',
      bgPanel: 'bg-white/80',
      textMain: 'text-[#4a1942] italic',
      textMuted: 'text-[#6a3962]',
      primary: 'bg-gradient-to-r from-[#ff9a56] to-[#ff6b9d] text-white italic shadow-[4px_4px_0_#4a1942]',
      border: 'border border-orange-300',
      shadow: 'shadow-lg shadow-orange-200',
      inputStyle: 'bg-white/90 border-2 border-orange-300 text-red-900',
    },
    variantC: {
      name: '薄荷绿松',
      bgApp: 'bg-gradient-to-b from-[#a8e6cf] via-[#56cfe1] to-[#4ea8de]',
      bgPanel: 'bg-white/80',
      textMain: 'text-[#1a4d2e] italic',
      textMuted: 'text-[#2a6d4e]',
      primary: 'bg-gradient-to-r from-[#a8e6cf] to-[#56cfe1] text-white italic shadow-[4px_4px_0_#1a4d2e]',
      border: 'border border-teal-300',
      shadow: 'shadow-lg shadow-teal-200',
      inputStyle: 'bg-white/90 border-2 border-teal-300 text-teal-900',
    },
    variantD: {
      name: '暗黑蒸汽',
      bgApp: 'bg-gradient-to-b from-[#2b1d52] via-[#1a0b3c] to-[#0a0420]',
      bgPanel: 'bg-purple-900/80',
      textMain: 'text-[#ff71ce] italic',
      textMuted: 'text-[#01cdfe]',
      primary: 'bg-gradient-to-r from-[#ff71ce] to-[#01cdfe] text-black italic shadow-[4px_4px_0_#ff71ce]',
      border: 'border border-pink-500',
      shadow: 'shadow-lg shadow-pink-500/50',
      inputStyle: 'bg-purple-900/90 border-2 border-pink-500 text-pink-300',
    },
  },

  // 10. Dark Academia
  'dark-academia': {
    variantA: {
      name: '经典学院',
      bgApp: 'bg-[#1a1716]',
      bgPanel: 'bg-[#2b2624] border border-[#4a403a]',
      textMain: 'text-[#d6cfc7]',
      textMuted: 'text-[#8f847a]',
      primary: 'bg-[#5c4d44] text-[#e8e4e1] border border-[#8f847a] hover:bg-[#736257] uppercase tracking-widest text-xs',
      border: 'border border-[#423833]',
      shadow: 'shadow-xl',
      inputStyle: 'bg-[#1f1b1a] border border-[#5c4d44] text-[#d6cfc7]',
    },
    variantB: {
      name: '深绿图书馆',
      bgApp: 'bg-[#0f1a0f]',
      bgPanel: 'bg-[#1a2a1a] border border-[#2a4a2a]',
      textMain: 'text-[#c7d6c7]',
      textMuted: 'text-[#7a8f7a]',
      primary: 'bg-[#3a5a3a] text-[#e1e8e1] border border-[#5a7a5a] hover:bg-[#4a6a4a] uppercase tracking-widest text-xs',
      border: 'border border-[#2a3a2a]',
      shadow: 'shadow-xl shadow-green-900/50',
      inputStyle: 'bg-[#0f1a0f] border border-[#3a5a3a] text-[#c7d6c7]',
    },
    variantC: {
      name: '深蓝书房',
      bgApp: 'bg-[#0a0f1a]',
      bgPanel: 'bg-[#1a1f2a] border border-[#2a3a4a]',
      textMain: 'text-[#c7cfd6]',
      textMuted: 'text-[#7a848f]',
      primary: 'bg-[#3a4a5a] text-[#e1e4e8] border border-[#5a6a7a] hover:bg-[#4a5a6a] uppercase tracking-widest text-xs',
      border: 'border border-[#2a3343]',
      shadow: 'shadow-xl shadow-blue-900/50',
      inputStyle: 'bg-[#0a0f1a] border border-[#3a4a5a] text-[#c7cfd6]',
    },
    variantD: {
      name: '浅色学院',
      bgApp: 'bg-[#f5f5dc]',
      bgPanel: 'bg-[#fffaf0] border border-[#d7ccc8]',
      textMain: 'text-[#3a2a1a]',
      textMuted: 'text-[#6a5a4a]',
      primary: 'bg-[#8a7a6a] text-[#fffaf0] border border-[#6a5a4a] hover:bg-[#7a6a5a] uppercase tracking-widest text-xs',
      border: 'border border-[#d7ccc8]',
      shadow: 'shadow-xl shadow-brown-200',
      inputStyle: 'bg-white border border-[#8a7a6a] text-[#3a2a1a]',
    },
  },
};

// Helper function to get color variant
export const getColorVariant = (themeId, variantKey = 'variantA') => {
  const variants = COLOR_VARIANTS[themeId];
  if (!variants) return null;
  return variants[variantKey] || variants.variantA;
};

// Helper function to merge theme with color variant
export const applyColorVariant = (baseTheme, variantKey = 'variantA') => {
  const variant = getColorVariant(baseTheme.id, variantKey);
  if (!variant) return baseTheme;

  return {
    ...baseTheme,
    ...variant,
  };
};
